services:
  mongodb:
    image: mongo:4.4.3
    volumes:
      - mongo-data:/data/db 
    restart: always 
    ports:
      - 27017:27017
    networks:
      - dbnetwork
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=Jason
      - MONGODB_INITDB_ROOT_PASSWORD=3lack3ox

  node.js:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://Jason:3lack3ox@express.hsxg7fd.mongodb.net/express
    ports:
      - 8081:3000  # Host port 8081 mapped to container port 3000
    
volumes:
  mongo-data:

networks:
  dbnetwork:
    driver: bridge
